volumes:
  pg_data:
  static:

services:
  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - /var/pg_data:/var/lib/postgresql/data
    networks:
      - ac-net
  backend:
    build: ./access_service/
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - postgres
    networks:
      - ac-net
  gateway:
    build: ./gateway/
    env_file: .env
    volumes:
      - static:/staticfiles/
    ports:
      - 127.0.0.1:9000:80
    depends_on:
      - postgres
      - backend
    networks:
      - ac-net
networks:
  ac-net:
    name: ac-net
