version: '3'

volumes:
  pg_data:
  static:

services:
  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - /var/pg_data:/var/lib/postgresql/data
    networks:
      - ac-net
  backend:
    build: ./access_service/
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - ac-net
networks:
  ac-net:
    name: ac-net