# Generated by Django 4.2.13 on 2024-08-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('name', models.TextField(verbose_name='Юр.лицо')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('type', models.TextField(max_length=40, verbose_name='Тип договора')),
            ],
            options={
                'verbose_name': 'Тип договора',
                'verbose_name_plural': 'Типы договоров',
            },
        ),
        migrations.CreateModel(
            name='Contragent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('name', models.TextField(max_length=40, verbose_name='Название контрагента')),
                ('person', models.TextField(max_length=60, verbose_name='Контактное лицо')),
                ('phone_number', models.CharField(max_length=40, verbose_name='Телефон контактного лица')),
                ('email', models.CharField(max_length=40, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('surname', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('patronym', models.CharField(blank=True, max_length=40, verbose_name='Отчество')),
                ('common_name', models.CharField(max_length=60, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=True)),
                ('is_contragent', models.BooleanField(default=False)),
                ('end_time', models.DateTimeField(null=True, verbose_name='Дата окончания работы')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='access_engine.company', verbose_name='Юр.лицо')),
                ('contract_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='access_engine.contract_type', verbose_name='Тип контракта')),
                ('contragent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='access_engine.contragent', verbose_name='Контрагент')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.CreateModel(
            name='ItAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('name', models.TextField(verbose_name='Название')),
                ('url_address', models.TextField(blank=True, verbose_name='URL-адрес')),
                ('ip_address', models.TextField(blank=True, verbose_name='IP адрес')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_assets', to='access_engine.employee', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'ИТ-актив',
                'verbose_name_plural': 'ИТ-активы',
            },
        ),
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('name', models.TextField(verbose_name='Действие')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('name', models.TextField(verbose_name='Название')),
                ('itasset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='access_engine.itasset', verbose_name='Роль / Полномочия')),
            ],
            options={
                'verbose_name': 'Полномочия',
                'verbose_name_plural': 'Полномочия',
            },
        ),
        migrations.CreateModel(
            name='TechAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('name', models.TextField(verbose_name='Имя')),
                ('is_active', models.BooleanField()),
                ('itasset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_accounts', to='access_engine.itasset', verbose_name='Сервис')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='techaccounts', to='access_engine.employee', verbose_name='Работник')),
                ('role', models.ManyToManyField(null=True, related_name='tech_accounts', to='access_engine.role', verbose_name='Роль / Полномочия')),
            ],
            options={
                'verbose_name': 'Технический аккаунт',
                'verbose_name_plural': 'Технические аккаунты',
            },
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('is_tech', models.BooleanField()),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='access_engine.employee', verbose_name='Работник')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='access_engine.role', verbose_name='Роль / Полномочия')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('log', models.TextField(verbose_name='Сообщение')),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='access_engine.logaction')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.AddField(
            model_name='contragent',
            name='duty_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contragents', to='access_engine.employee', verbose_name='Отвественный от Сравни'),
        ),
    ]
