# Generated by Django 4.2.13 on 2024-08-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techaccount',
            name='role',
            field=models.ManyToManyField(related_name='tech_accounts', to='access_engine.role', verbose_name='Роль / Полномочия'),
        ),
    ]
