# Generated by Django 4.2.13 on 2024-08-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_engine', '0004_alter_absuser_admin_rights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.TextField(verbose_name='Действие'),
        ),
        migrations.DeleteModel(
            name='LogAction',
        ),
    ]
