# Generated by Django 4.2.13 on 2024-08-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_engine', '0006_alter_employee_company_alter_employee_contragent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания работы'),
        ),
    ]
