# Generated by Django 4.2.13 on 2024-08-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_engine', '0007_alter_employee_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='url_address',
            field=models.CharField(blank=True, max_length=100, verbose_name='URL-адрес'),
        ),
    ]
