# Generated by Django 4.2.13 on 2024-08-26 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_engine', '0008_alter_itasset_ip_address_alter_itasset_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='itasset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='access_engine.itasset', verbose_name='ИТ Актив'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.TextField(verbose_name='Название роли'),
        ),
    ]
