# Generated by Django 4.2.13 on 2024-08-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_engine', '0009_alter_role_itasset_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Название роли'),
        ),
    ]
