# Generated by Django 4.2.13 on 2024-08-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_engine', '0010_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='right',
            name='techaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='techaccounts', to='access_engine.techaccount', verbose_name='Тех.учетка'),
        ),
        migrations.AlterField(
            model_name='right',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='access_engine.employee', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='techaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
