# Generated by Django 4.2.13 on 2024-08-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_engine', '0011_right_techaccount_alter_right_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techaccount',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Имя'),
        ),
    ]
