# Generated by Django 4.2.13 on 2024-08-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_engine', '0012_alter_techaccount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contragent',
            name='email',
            field=models.CharField(max_length=80, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Название контрагента'),
        ),
        migrations.AlterField(
            model_name='contragent',
            name='person',
            field=models.CharField(max_length=80, verbose_name='Контактное лицо'),
        ),
    ]
