# Generated by Django 4.2.13 on 2024-08-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_engine', '0013_alter_contragent_email_alter_contragent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contragent',
            name='duty_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contragents', to='access_engine.employee', verbose_name='Отвественный от компании'),
        ),
    ]
