# Generated by Django 4.2.13 on 2024-08-28 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_engine', '0016_remove_techaccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='right',
            name='itasset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='access_engine.itasset', verbose_name='ИТ Актив'),
        ),
    ]
