# Generated by Django 4.2.13 on 2025-04-06 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_engine', '0017_right_itasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='access_engine.company', verbose_name='Юр.лицо'),
        ),
    ]
