# Generated by Django 4.2.13 on 2025-04-06 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_engine', '0018_itasset_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название платежного метода')),
                ('expiration_date', models.DateField(null=True)),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BillingMethods', to='access_engine.company', verbose_name='Юр.лицо')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='access_engine.employee', verbose_name='Ответственный сотрудник')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
